### PR TITLE
Third time's a charm?

### PR DESCRIPTION
**Pull request by scarolan**
Ok, I put the Rakefile back in place.  This should pass the Travis CI build now.

### CODE REVIEW

**Comment by flaccid** [comment]
@fnichol can we work together to get this one merged?

**Comment by scarolan** [comment]
Sure, I'm game.

**Comment by flaccid** [comment]
Because I need to get something going at work I've forked from here and created this branch, https://github.com/flaccid/chef-puppet/tree/flaccid_updates_fixes. Perhaps I'll do all my enhancements then run through each failed commit above and fix, then you can merge into scarolan:master and then @fnichol can then merge this PR?

**Comment by flaccid** [comment]
Ok I have created https://github.com/scarolan/chef-puppet/pull/1. If both get merged, then we can remove our forks and continue contributing to the original repo :)

**Comment by flaccid** [comment]
@scarolan @fnichol bump bump :) Can we get this all merged back up to the original repo now?
I'll do another couple of commits to fix the travis issues above.

**Comment by flaccid** [comment]
@scarolan @fnichol actually all is passing already in my pull https://github.com/scarolan/chef-puppet/pull/1. Can we hit the merge button twice, one each? :)

**Comment by flaccid** [comment]
@fnichol can we get some action here?

**Pull request closed without merging**
